name: Compile PDF

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xu-cheng/texlive-full

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Compile PDF
        run: |
          make monografia

      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
